apiVersion: batch/v1
kind: Job
metadata:
  name: producer-service-job
  namespace: demo
  labels:
    app: producer-service
spec:
  template:
    metadata:
      labels:
        app: producer-service
    spec:
      containers:
        - name: producer-service
          image: producer-service:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: RABBITMQ_URL
              value: "amqp://admin:adminpassword@my-rabbitmq.demo.svc.cluster.local:5672/"
            - name: OTLP_PORT
              value: "4318"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "$(NODE_NAME):$(OTLP_PORT)"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      restartPolicy: Never
  backoffLimit: 4